---
- hosts: dc
  become: yes
  become_method: sudo
  vars:
    init: false
  roles:
    - xbps-repoconf
    - network
    - sshd
    - core-daemons
    - core-programs
    - slapd
    - krb5kdc
    - netlogon
    - upsmon
    - netdata
